services:
  backend:
    command: sh -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn larvixon_site.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    environment:
      - DEBUG=False
      - AZURE_ACCOUNT_NAME=${AZURE_ACCOUNT_NAME}
      - AZURE_ACCOUNT_KEY=${AZURE_ACCOUNT_KEY}
      - AZURE_CONTAINER=${AZURE_CONTAINER}
    volumes:
      # Remove source code mount for production
      - static_volume:/app/staticfiles

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles:ro
    depends_on:
      - backend
